name: Build

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.21"

      - name: Run GoReleaser
        id: goreleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: build --skip=validate

      - name: Generate SBOM from the source
        uses: anchore/sbom-action@v0
        with:
          path: .
          artifact-name: sbom.spdx.json
          upload-artifact: true
          config: .github/edgebit/source-syft.yaml
          syft-version: v1.5.0

      - name: Write out the metadata
        run: |
          cat > /tmp/metadata.json <<EOF
            {
              "pr-number": "${{ github.event.number }}",
              "tags": "${{ github.ref == 'refs/heads/main' && 'latest' || '' }}",
              "commit-sha": "${{github.sha}}"
            }
          EOF

      - uses: actions/upload-artifact@v3
        name: Save the metadata as an artifact
        with:
          name: metadata.json
          path: /tmp/metadata.json
